security:
    encoders:
        %mes_user.class%:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        main:
            id: mes_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            simple_form:
                authenticator: mes_authenticator
                check_path: mes_login_check
                login_path: mes_login
                username_parameter: __username
                password_parameter: __password
            logout:
                path:   mes_logout
            anonymous: ~
            
    access_control:
        - { path: ^/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/uzytkownik, roles: IS_AUTHENTICATED_FULLY }